# Generated by Django 4.0.3 on 2022-04-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_building_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='town',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='department_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
